# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_month', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts_goal', models.PositiveIntegerField()),
                ('new_clients_goal', models.PositiveIntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='QueryPlansClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=True)),
                ('transfer', models.BooleanField(default=True)),
                ('share', models.BooleanField(default=True)),
                ('empower', models.BooleanField(default=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Deactivated')])),
                ('is_chosen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QueryPlansManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_receiver', models.CharField(max_length=150, null=True)),
                ('type_operation', models.PositiveIntegerField(choices=[(1, 'Transfer'), (2, 'Share'), (3, 'Empower')])),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Deactivated'), (3, 'Processing')])),
                ('count_queries', models.PositiveIntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('last_name', models.CharField(max_length=55, null=True)),
                ('type_contact', models.PositiveIntegerField(choices=[(1, 'Effective'), (2, 'Non Effective'), (3, 'Effective paid')])),
                ('type_client', models.CharField(choices=[('n', 'Natural'), ('b', 'Business')], max_length=1)),
                ('document_type', models.PositiveIntegerField(choices=[(1, 'DNI'), (2, 'Passport'), (3, 'Foreign Card')])),
                ('document_number', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=150, null=True)),
                ('civil_state', models.CharField(choices=[('c', 'cohabiting'), ('e', 'separated'), ('m', 'married'), ('w', 'widower'), ('d', 'divorced'), ('s', 'single')], max_length=1, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('institute', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_description', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.CharField(max_length=250, null=True)),
                ('about', models.CharField(blank=True, max_length=250, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=14, null=True)),
                ('telephone', models.CharField(blank=True, max_length=14, null=True)),
                ('ocupation', models.PositiveIntegerField(choices=[(1, 'Employer'), (2, 'Independent worker'), (3, 'Employee'), (4, 'Worker'), (5, 'Worker in a family business'), (6, 'Home worker'), (7, 'Other')], default=7, null=True)),
                ('profession', models.CharField(max_length=45, null=True)),
                ('business_name', models.CharField(max_length=45, null=True)),
                ('commercial_reason', models.CharField(max_length=45, null=True)),
                ('agent_firstname', models.CharField(max_length=45, null=True)),
                ('agent_lastname', models.CharField(max_length=45, null=True)),
                ('sex', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('latitude', models.CharField(blank=True, max_length=45)),
                ('longitude', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(max_length=45, null=True)),
                ('ruc', models.CharField(blank=True, max_length=40, null=True)),
                ('other_objection', models.CharField(blank=True, max_length=120, null=True)),
                ('foreign_address', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Address')),
                ('ciiu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ciiu')),
                ('economic_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.EconomicSector')),
                ('level_instruction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.LevelInstruction')),
                ('nationality', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Countries')),
                ('residence_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residence_contact', to='api.Countries', verbose_name='residence country contact')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Seller')),
            ],
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='ciiu',
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='economic_sector',
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='level_instruction',
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='objection',
        ),
        migrations.RemoveField(
            model_name='sellercontactnoefective',
            name='seller',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='calification',
            new_name='qualification',
        ),
        migrations.RemoveField(
            model_name='monthlyfee',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='monthlyfee',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='monthlyfee',
            name='sale_detail',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='account_number_drawer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='agency_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='check_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='credit_card_cvc',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='credit_card_exp_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='credit_cart_number',
        ),
        migrations.RemoveField(
            model_name='queryplansacquired',
            name='client',
        ),
        migrations.RemoveField(
            model_name='queryplansacquired',
            name='is_chosen',
        ),
        migrations.AddField(
            model_name='message',
            name='file_preview_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='monthlyfee',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Sale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='monthly_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.MonthlyFee'),
        ),
        migrations.AddField(
            model_name='query',
            name='available_requeries',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Paid')], default=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='pay_before',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='objection',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='payment',
            name='authorization_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='observations',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Declined')], default=1),
        ),
        migrations.AlterField(
            model_name='sale',
            name='place',
            field=models.CharField(default='por definir', max_length=100),
        ),
        migrations.DeleteModel(
            name='SellerContactNoEfective',
        ),
        migrations.AddField(
            model_name='queryplansmanage',
            name='acquired_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_acquired_plan', to='api.QueryPlansAcquired'),
        ),
        migrations.AddField(
            model_name='queryplansmanage',
            name='new_acquired_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.QueryPlansAcquired'),
        ),
        migrations.AddField(
            model_name='queryplansmanage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Client'),
        ),
        migrations.AddField(
            model_name='queryplansmanage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_sender', to='api.Client'),
        ),
        migrations.AddField(
            model_name='queryplansclient',
            name='acquired_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.QueryPlansAcquired'),
        ),
        migrations.AddField(
            model_name='queryplansclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Client'),
        ),
        migrations.AddField(
            model_name='objectionslist',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SellerContact'),
        ),
        migrations.AddField(
            model_name='objectionslist',
            name='objection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Objection'),
        ),
        migrations.AddField(
            model_name='declinator',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Query'),
        ),
        migrations.AddField(
            model_name='declinator',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Specialist'),
        ),
    ]
