# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products_seller_no_billable',
            new_name='ProductsSellerNoBillable',
        ),
        migrations.AddField(
            model_name='seller',
            name='ciiu',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='residence_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residence', to='api.Countries'),
        ),
    ]
