# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-10 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180921_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='file_preview_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='file_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='operation_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='operation number'),
        ),
    ]
