# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171221_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bank')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_file', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('validity_months', models.PositiveIntegerField()),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeeMonthSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.DateField()),
                ('fee_plans', models.PositiveIntegerField()),
                ('fee_contacts', models.PositiveIntegerField()),
                ('complete_fee_products', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='LogPaymentsCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('successful', models.BooleanField()),
                ('description', models.CharField(max_length=50)),
                ('code_api', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MatchAcquired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cause', models.TextField()),
                ('status', models.CharField(choices=[('0', 'Requested'), ('1', 'Accepted'), ('2', 'Declined')], max_length=1)),
                ('paid_by_client', models.BooleanField(default=True)),
                ('paid_by_specialist', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='MatchAcquiredFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=100)),
                ('type_file', models.CharField(choices=[('0', 'Image'), ('1', 'Voice'), ('2', 'Document')], max_length=1)),
                ('match_acquired', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MatchAcquired')),
            ],
        ),
        migrations.CreateModel(
            name='MatchAcquiredLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_on', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('0', 'Requested'), ('1', 'Accepted'), ('2', 'Declined')], max_length=1)),
                ('declined', models.NullBooleanField()),
                ('declined_motive', models.CharField(max_length=255, null=True)),
                ('match_acquired', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.MatchAcquired')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_order_number', models.PositiveIntegerField()),
                ('fee_quantity', models.PositiveIntegerField()),
                ('reference_number', models.CharField(max_length=20)),
                ('pay_before', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Paid')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationsBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='message')),
                ('viewed', models.BooleanField(default=False, verbose_name='viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('operation_number', models.CharField(max_length=12)),
                ('agency_code', models.CharField(max_length=10)),
                ('account_number_drawer', models.CharField(max_length=50)),
                ('check_number', models.CharField(max_length=50)),
                ('credit_cart_number', models.CharField(max_length=30)),
                ('credit_card_cvc', models.CharField(max_length=3)),
                ('credit_card_exp_date', models.DateField()),
                ('authorization_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Accepted'), ('2', 'Declined')], max_length=1)),
                ('observations', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200, null=True)),
                ('changed_on', models.DateTimeField()),
                ('status_log', models.CharField(choices=[('0', 'Requested'), ('1', 'Requested Derived'), ('2', 'Pending Response'), ('3', 'Pending Main Response'), ('4', 'Answered Main'), ('5', 'Answered'), ('6', 'Absolved Main'), ('7', 'Absolved')], max_length=1)),
                ('derived', models.NullBooleanField()),
                ('declined', models.NullBooleanField()),
                ('declined_motive', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('query_quantity', models.IntegerField()),
                ('validity_months', models.PositiveIntegerField()),
                ('maximum_response_time', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryPlansAcquired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('validity_months', models.PositiveIntegerField()),
                ('available_queries', models.PositiveIntegerField()),
                ('activation_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('available_requeries', models.PositiveIntegerField()),
                ('maximum_response_time', models.PositiveIntegerField()),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Client')),
                ('query_plans', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.QueryPlans')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('is_fee', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Client')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pin_code', models.CharField(max_length=50)),
                ('is_billable', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Contract')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ProductType')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='SellerNonBillablePlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('number_month', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_plans', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.QueryPlans')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Seller')),
            ],
        ),
        migrations.RenameModel(
            old_name='Plan',
            new_name='Clasification',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='category',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='role',
        ),
        migrations.RemoveField(
            model_name='alertcategory',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='contractcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='client',
        ),
        migrations.RemoveField(
            model_name='culqipayment',
            name='credit_cartd',
        ),
        migrations.RemoveField(
            model_name='declinedmotive',
            name='query_id',
        ),
        migrations.RemoveField(
            model_name='declinedmotive',
            name='specialist_id',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='purchase',
        ),
        migrations.DeleteModel(
            name='FeeNextMonthSeller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='productssellernobillable',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productssellernobillable',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='client',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='query_ptr',
        ),
        migrations.DeleteModel(
            name='Quota',
        ),
        migrations.RemoveField(
            model_name='specialistcontract',
            name='client',
        ),
        migrations.RemoveField(
            model_name='specialistcontract',
            name='specialist',
        ),
        migrations.DeleteModel(
            name='TransactionCode',
        ),
        migrations.RenameField(
            model_name='messagefile',
            old_name='url',
            new_name='url_file',
        ),
        migrations.RemoveField(
            model_name='category',
            name='payment_per_answer',
        ),
        migrations.AddField(
            model_name='category',
            name='fixed_commission',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='variable_commission',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='code_cellphone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prefix_cellphone', to='api.Countries'),
        ),
        migrations.AddField(
            model_name='user',
            name='code_telephone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prefix_telephone', to='api.Countries'),
        ),
        migrations.AlterField(
            model_name='query',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='payment_per_answer',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AlertCategory',
        ),
        migrations.DeleteModel(
            name='ContractCategory',
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.DeleteModel(
            name='CulqiPayment',
        ),
        migrations.DeleteModel(
            name='DeclinedMotive',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='Interval',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductsSellerNoBillable',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='QueryLog',
        ),
        migrations.DeleteModel(
            name='SpecialistContract',
        ),
        migrations.AddField(
            model_name='queryplansacquired',
            name='sale_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SaleDetail'),
        ),
        migrations.AddField(
            model_name='queryplans',
            name='clasification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Clasification'),
        ),
        migrations.AddField(
            model_name='queryplans',
            name='non_billable',
            field=models.ManyToManyField(through='api.SellerNonBillablePlans', to='api.Seller'),
        ),
        migrations.AddField(
            model_name='queryplans',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ProductType'),
        ),
        migrations.AddField(
            model_name='querylogs',
            name='from_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='al_especialista', to='api.Specialist'),
        ),
        migrations.AddField(
            model_name='querylogs',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Query'),
        ),
        migrations.AddField(
            model_name='querylogs',
            name='to_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='del_especialista', to='api.Specialist'),
        ),
        migrations.AddField(
            model_name='payment',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Bank'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.PaymentType'),
        ),
        migrations.AddField(
            model_name='notificationsback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyfee',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Payment'),
        ),
        migrations.AddField(
            model_name='monthlyfee',
            name='sale_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SaleDetail'),
        ),
        migrations.AddField(
            model_name='matchacquired',
            name='sale_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SaleDetail'),
        ),
        migrations.AddField(
            model_name='matchacquired',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Specialist'),
        ),
        migrations.AddField(
            model_name='match',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ProductType'),
        ),
        migrations.AddField(
            model_name='match',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Category'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ContractType'),
        ),
        migrations.AddField(
            model_name='category',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Contract'),
        ),
        migrations.AddField(
            model_name='query',
            name='acquired_plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.QueryPlansAcquired'),
            preserve_default=False,
        ),
    ]
