# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171221_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foreign_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='address'),
        ),
    ]
