# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180209_1224'),
        ('api', '0007_auto_20180130_1414'),
    ]

    operations = [
    ]
