# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20180216_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryplansacquired',
            old_name='cliente',
            new_name='client',
        ),
        migrations.AddField(
            model_name='message',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=45, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='nick',
            field=models.CharField(blank=True, max_length=45, verbose_name='nick'),
        ),
        migrations.AddField(
            model_name='query',
            name='changed_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='queryplansacquired',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queryplansacquired',
            name='plan_name',
            field=models.CharField(default='C2461258333', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queryplansacquired',
            name='query_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='ciiu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ciiu'),
        ),
        migrations.AlterField(
            model_name='matchacquiredfiles',
            name='type_file',
            field=models.CharField(choices=[('0', 'Image'), ('1', 'Voice'), ('2', 'Document'), ('3', 'Video')], max_length=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Specialist'),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='type_file',
            field=models.CharField(choices=[('0', 'Image'), ('1', 'Voice'), ('2', 'Document'), ('3', 'Video')], max_length=1),
        ),
        migrations.AlterField(
            model_name='query',
            name='acquired_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.QueryPlansAcquired'),
        ),
        migrations.AlterField(
            model_name='query',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Specialist'),
        ),
        migrations.AlterField(
            model_name='queryplansacquired',
            name='activation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='queryplansacquired',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='ciiu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ciiu'),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='ciiu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ciiu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foreign_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='foreign address'),
        ),
    ]
