# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180227_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistMessageList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.CharField(blank=True, max_length=240)),
                ('nick', models.CharField(blank=True, max_length=40)),
                ('date', models.DateField(blank=True)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('total', models.IntegerField(blank=True)),
                ('client', models.IntegerField(blank=True)),
                ('specialist', models.IntegerField(blank=True)),
            ],
            options={
                'managed': False,
                'db_table': 'specialist_message_list',
            },
        ),
        migrations.RemoveField(
            model_name='messagefile',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='nick',
        ),
        migrations.AddField(
            model_name='message',
            name='content_type',
            field=models.CharField(choices=[('0', 'Text'), ('1', 'Image'), ('2', 'Video'), ('3', 'Voice'), ('4', 'Document')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='file_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='message_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ref', to='api.Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchacquiredfiles',
            name='type_file',
            field=models.CharField(choices=[('1', 'Image'), ('2', 'Voice'), ('3', 'Document')], max_length=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_type',
            field=models.CharField(blank=True, choices=[('q', 'query'), ('r', 'requery'), ('a', 'answer')], max_length=1),
        ),
        migrations.AlterField(
            model_name='query',
            name='acquired_plan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='api.QueryPlansAcquired'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='ruc',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.CharField(max_length=45, verbose_name='document number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ruc',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='MessageFile',
        ),
    ]
