# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180406_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='ocupation',
            field=models.PositiveIntegerField(choices=[(1, 'Employer'), (2, 'Independent worker'), (3, 'Employee'), (4, 'Worker'), (5, 'Worker in a family business'), (6, 'Home worker'), (7, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='matchacquired',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Declined')]),
        ),
        migrations.AlterField(
            model_name='matchacquiredfiles',
            name='type_file',
            field=models.PositiveIntegerField(choices=[(2, 'Image'), (3, 'Voice'), (4, 'Document')]),
        ),
        migrations.AlterField(
            model_name='matchacquiredlog',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Declined')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='content_type',
            field=models.PositiveIntegerField(choices=[(1, 'Text'), (2, 'Image'), (3, 'Video'), (4, 'Voice'), (5, 'Document')]),
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Paid')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Declined')]),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Answered'), (4, 'To score'), (5, 'Absolved')]),
        ),
        migrations.AlterField(
            model_name='querylogs',
            name='status_log',
            field=models.PositiveIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Answered'), (4, 'To score'), (5, 'Absolved')]),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='document_type',
            field=models.PositiveIntegerField(choices=[(1, 'DNI'), (2, 'Passport'), (3, 'Foreign Card')]),
        ),
        migrations.AlterField(
            model_name='sellercontactnoefective',
            name='ocupation',
            field=models.PositiveIntegerField(choices=[(1, 'Employer'), (2, 'Independent worker'), (3, 'Employee'), (4, 'Worker'), (5, 'Worker in a family business'), (6, 'Home worker'), (7, 'Other')], default=7, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.PositiveIntegerField(choices=[(1, 'DNI'), (2, 'Passport'), (3, 'Foreign Card')], verbose_name='type document'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='nick'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Activate'), (3, 'Reject'), (4, 'Deactivated')], default=1),
        ),
        migrations.AddField(
            model_name='recoverypassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.GroupMessage'),
        ),
    ]
