# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='cv',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(default='preview.png', max_length=250, null=True),
        ),
    ]
