# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171010_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.CharField(max_length=45),
        ),
    ]
