# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171010_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_exact',
            field=models.CharField(max_length=150),
        ),
    ]
